export const jsonData = [
    {name: 'Ashish'},
    {name: 'Harsh'},
    {name: 'Harshit'},
    {name: 'utipa'},
    {name: 'Deepak'},
    {name: 'Garima'},
    {name: 'Aashmi'},
    {name: 'Rashmi'},
    {name: 'sumit'},
    {name: 'Rashi'},
    {name: 'diiplo'},
    {name: 'jivaa'},
    {name: 'erica'},
    {name: 'ron'},
    {name: 'Veer'},
    {name: 'Batit'},
    {name: 'Laef'},
];